# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: v2025.04.0
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name: ""
  scenarios:
    enable: true
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: true # Set to false if problems regarding missing directories occur

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - 1024
  opts:
  - Co2L-1h
  
  planning_horizons:
  - 2020
  # - 2030
  # - 2040
  #- 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  prepare_links_p_nom: false
  retrieve_databundle: false
  retrieve_sector_databundle: false
  retrieve_cost_data: true
  build_cutout: true
  retrieve_cutout: false
  build_natura_raster: false
  retrieve_natura_raster: true
  custom_busmap: false
  drop_leap_day: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2020: 0.701


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  voltages: [220., 300., 330., 380., 400., 500., 750.]
  base_network: osm-prebuilt
  osm-prebuilt-version: 0.6
  gaslimit_enable: false
  gaslimit: false
  co2limit_enable: false
  co2limit: 7.75e+7
  co2base: 1.487e+9

  operational_reserve:
    activate: false
    epsilon_load: 0.02
    epsilon_vres: 0.02
    contingency: 4000

  max_hours:
    battery: 6
    H2: 168

  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]
    StorageUnit: [] # battery, H2
    Store: [battery, H2]
    Link: [] # H2 pipeline

  powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
  custom_powerplants: false
  everywhere_powerplants: []

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, hydro]

  estimate_renewable_capacities:
    enable: true
    from_gem: true
    year: 2020
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar

  autarky:
    enable: false
    by_country: false

  transmission_limit: vopt

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#atlite

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#renewable
# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#lines
lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    330.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"
    400.: "Al/St 240/40 4-bundle 380.0"
    500.: "Al/St 240/40 4-bundle 380.0"
    750.: "Al/St 560/50 4-bundle 750.0"
  s_max_pu: 0.7
  s_nom_max: .inf
  max_extension: 20000 #MW
  length_factor: 1.25
  reconnect_crimea: true
  under_construction: 'keep' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity for lines in grid extract
  dynamic_line_rating:
    activate: false
    cutout: default
    correction_factor: 0.95
    max_voltage_difference: false
    max_line_rating: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#links
links:
  p_max_pu: 1.0
  p_nom_max: .inf
  max_extension: 30000 #MW
  length_factor: 1.25
  under_construction: 'keep' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity for lines in grid extract

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    tyndp2020: true
    nep: true
    manual: true
  skip:
  - upgraded_lines
  - upgraded_links
  status:
  - under_construction
  - in_permitting
  - confirmed
    #- planned_not_yet_permitted
    #- under_consideration
  new_link_capacity: zero #keep or zero

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transformers
transformers:
  x: 0.1
  s_nom: 2000.
  type: ''

# docs-load in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#load
load:
  interpolate_limit: 3
  time_shift_for_large_gaps: 1w
  manual_adjustments: true # false
  scaling_factor: 1.0
  fixed_year: false # false or year (e.g. 2013)
  supplement_synthetic: true
  distribution_key:
    gdp: 0.6
    population: 0.4

# docs
# TODO: PyPSA-Eur merge issue in prepare_sector_network.py
# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# (e.g. battery or H2 storage) or have different year-dependent costs
# in PyPSA-Eur-Sec
pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  - nuclear
  StorageUnit:
  - PHS
  - hydro
  Store: []

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#energy
energy:
  energy_totals_year: 2019
  base_emissions_year: 1990
  emissions: CO2

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#biomass
biomass:
  year: 2030
  scenario: ENS_Med
  classes:
    solid biomass:
    - Agricultural waste
    - Fuelwood residues
    - Secondary Forestry residues - woodchips
    - Sawdust
    - Residues from landscape care
    not included:
    - Sugar from sugar beet
    - Rape seed
    - "Sunflower, soya seed "
    - Bioethanol barley, wheat, grain maize, oats, other cereals and rye
    - Miscanthus, switchgrass, RCG
    - Willow
    - Poplar
    - FuelwoodRW
    - C&P_RW
    biogas:
    - Manure solid, liquid
    - Sludge
    municipal solid waste:
    - Municipal waste
  share_unsustainable_use_retained:
    2020: 1
    2025: 0.66
    2030: 0.33
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  share_sustainable_potential_available:
    2020: 0
    2025: 0.33
    2030: 0.66
    2035: 1
    2040: 1
    2045: 1
    2050: 1


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solar-thermal
solar_thermal:
  clearsky_model: simple  # should be "simple" or "enhanced"?
  orientation:
    slope: 45.
    azimuth: 180.
  cutout: default

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#existing-capacities
existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # heat grouping years >= baseyear will be ignored
  threshold_capacity: 10
  default_heating_lifetime: 20
  conventional_carriers:
  - lignite
  - coal
  - oil
  - uranium

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#adjustments
adjustments:
  electricity: false
  sector:
    factor:
      Link:
        electricity distribution grid:
          capital_cost: 1.0
    absolute: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: false
    curtailment_mode: false
    noisy_costs: true
    skip_iterations: true
    rolling_horizon: false
    seed: 123
    custom_extra_functionality: "../data/custom_extra_functionality.py"
    # io_api: "direct"  # Increases performance but only supported for the highs and gurobi solvers
    # options that go into the optimize function
    track_iterations: false
    min_iterations: 2
    max_iterations: 3
    transmission_losses: 2
    linearized_unit_commitment: true
    horizon: 365
    post_discretization:
      enable: false
      line_unit_size: 1700
      line_threshold: 0.3
      link_unit_size:
        DC: 2000
        H2 pipeline: 1200
        gas pipeline: 1500
      link_threshold:
        DC: 0.3
        H2 pipeline: 0.3
        gas pipeline: 0.3
      fractional_last_unit_size: false
    keep_files: false
    model_kwargs:
      solver_dir: "/tmp"

  agg_p_nom_limits:
    agg_offwind: false
    include_existing: false
    file: data/agg_p_nom_minmax.csv

  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false

  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/dev/options/definitions/
      threads: 1
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    highs-simplex:
      solver: "simplex"
      parallel: "on"
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      random_seed: 123
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
    gurobi-numeric-focus:
      NumericFocus: 3       # Favour numeric stability over speed
      method: 2             # barrier
      crossover: 0          # do not use crossover
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-4
      OptimalityTol: 1.e-4
      ObjScale: -0.5
      threads: 8
      Seed: 123
    gurobi-fallback:        # Use gurobi defaults
      crossover: 0
      method: 2             # barrier
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-5
      OptimalityTol: 1.e-5
      Seed: 123
      threads: 8
    cplex-default:
      threads: 4
      lpmethod: 4 # barrier
      solutiontype: 2 # non basic solution, ie no crossover
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    copt-default:
      Threads: 8
      LpMethod: 2
      Crossover: 0
      RelGap: 1.e-6
      Dualize: 0
    copt-gpu:
      LpMethod: 6
      GPUMode: 1
      PDLPTol: 1.e-5
      Crossover: 0
    cbc-default: {} # Used in CI
    glpk-default: {} # Used in CI

  check_objective:
    enable: false
    expected_value: None
    atol: 1_000_000
    rtol: 0.01

  mem_mb: 30000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  memory_logging_frequency: 30 # in seconds
  runtime: 6h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/
