# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-eur

channels:
- conda-forge
- bioconda
dependencies:
- python>=3.8

- pypsa>=0.26.1
- linopy
- dask

  # Dependencies of the workflow itself
- xlrd
- openpyxl!=3.1.1
- pycountry
- seaborn
- yaml
- pytables
- lxml
- numpy
- pandas>=2.1
- geopandas>=0.11.0
- xarray>=2023.11.0
- rioxarray
- netcdf4
- networkx
- scipy
- glpk
- shapely>=2.0
- pyscipopt
- matplotlib
- proj
- fiona
- country_converter
- geopy
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- pre-commit
- gurobi::gurobi
  # Keep in conda environment when calling ipython
- ipython

